name: complex

on: push

jobs:
        ubuntu-job:
                name: First job
                runs-on: ubuntu-latest
                steps:
                - run: date
        windows-job:
                name: Second job
                runs-on: windows-latest
                steps:
                - run: "Get-Date"
        macos-job: 
                name: third job
                runs-on: macos-latest
                steps:
                - run: "google-chrome --version"          
        depends-job:
                needs: [ubuntu-job, windows-job, macos-job]
                name: forth job
                runs-on: ubuntu-latest
                steps:
                - run: "google-chrome --version"
